# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = "ubuntu/trusty64"

    config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

    config.vm.provision :shell, inline: "sudo usermod -a -G www-data vagrant"
    config.vm.provision :shell, path: "./support-files/vagrant/provision.sh"

    config.vm.synced_folder "./", "/opt/cass", type: "smb", owner: "www-data", group: "www-data"
    config.vm.synced_folder "./support-files", "/support-files", type: "smb"

    config.vm.network "forwarded_port", guest: 3000, host: 8080 # www
    config.vm.network "forwarded_port", guest: 3001, host: 8081 # mongo-express
    config.vm.network "forwarded_port", guest: 3002, host: 8082 # react-php
    config.vm.network "forwarded_port", guest: 3003, host: 8083 # pimp
    config.vm.network "forwarded_port", guest: 27017, host: 27017 # mongo

    config.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "1024"
    end
end
